### ISSUE TITLE
Improve style of information message on bookings page

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/rcmod-wp-bookings-ui#46]
### Problem
Information message on bookings page is not noticeable. 

### Solution
ONLY on the Bookings page, the span with class="page-title-description" should have the following CSS applied to it:
```css
.selector {
    top: -3px;
    position: relative;
    margin-left: 10px;
    padding: 7px 15px;
    background-color: #fddc0d;
    font-size: 0.8rem;
    font-weight: bold;
    border-radius: 4px;
}
```
